# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lodgers.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_lodgers(object):
    def setupUi(self, lodgers):
        lodgers.setObjectName("lodgers")
        lodgers.resize(1087, 593)
        lodgers.setMinimumSize(QtCore.QSize(1087, 593))
        lodgers.setMaximumSize(QtCore.QSize(1087, 593))
        self.centralwidget = QtWidgets.QWidget(lodgers)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 530, 209, 40))
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButton_8.setObjectName("pushButton_8")

        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setEnabled(True)
        self.pushButton_9.setGeometry(QtCore.QRect(600, 392, 209, 40))
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButton_9.setObjectName("pushButton_9")

        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setGeometry(QtCore.QRect(850, 392, 209, 40))
        self.pushButton_10.setAutoFillBackground(False)
        self.pushButton_10.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButton_10.setObjectName("pushButton_10")

        self.tableView_1 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_1.setGeometry(QtCore.QRect(10, 20, 551, 411))
        self.tableView_1.setObjectName("tableView_1")
        lodgers.setCentralWidget(self.centralwidget)

        self.retranslateUi(lodgers)
        QtCore.QMetaObject.connectSlotsByName(lodgers)

    def retranslateUi(self, lodgers):
        _translate = QtCore.QCoreApplication.translate
        lodgers.setWindowTitle(_translate("lodgers", "Проживающие"))
        self.pushButton_8.setText(_translate("lodgers", "Назад"))
        self.pushButton_9.setText(_translate("RoomWindow", "Добавить запись"))
        self.pushButton_10.setText(_translate("RoomWindow", "Удалить запись"))