# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lodgers.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Rooms(object):
    def setupUi(self, rooms):
        rooms.setObjectName("rooms")
        rooms.resize(1087, 593)
        rooms.setMinimumSize(QtCore.QSize(1087, 593))
        rooms.setMaximumSize(QtCore.QSize(1087, 593))
        self.centralwidget = QtWidgets.QWidget(rooms)
        self.centralwidget.setObjectName("centralwidget")


        self.retranslateUi(rooms)
        QtCore.QMetaObject.connectSlotsByName(rooms)

    def retranslateUi(self, rooms):
        _translate = QtCore.QCoreApplication.translate
        rooms.setWindowTitle(_translate("rooms", "  "))
